version: '3'

services:
  web:
    image: php:7.4-apache
    volumes:
      - ./src/index.php:/var/www/html/index.php
      - ./apache-config.conf:/etc/apache2/conf-available/custom-config.conf
    ports:
      - "80:80"
    depends_on:
      - db
    command: /bin/bash -c "a2enconf custom-config && apache2-foreground"

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:

